name: test

on: [push, pull_request]

env:
  ENABLE_WERROR: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-2022, windows-2025, windows-11-arm]
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4', '3.5', 'head', 'debug']
        exclude:
        - { os: macos-latest, ruby: '2.5' }
        - { os: macos-latest, ruby: 'asan' }
        - { os: windows-2022, ruby: '3.5' }
        - { os: windows-2022, ruby: 'debug' }
        - { os: windows-2025, ruby: '3.5' }
        - { os: windows-2025, ruby: 'debug' }
        - { os: windows-11-arm, ruby: '2.5' }
        - { os: windows-11-arm, ruby: '2.6' }
        - { os: windows-11-arm, ruby: '2.7' }
        - { os: windows-11-arm, ruby: '3.0' }
        - { os: windows-11-arm, ruby: '3.1' }
        - { os: windows-11-arm, ruby: '3.2' }
        - { os: windows-11-arm, ruby: '3.3' }
        - { os: windows-11-arm, ruby: '3.5' }
        - { os: windows-11-arm, ruby: 'debug' }
        include:
          # CRuby < 2.6 does not support macos-arm64, so test those on amd64 instead
        - { os: macos-13, ruby: '2.5' }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: bundle exec rake
      run: |
        ruby -v
        bundle exec rake
